### ISSUE TITLE
underpromotion issue? 

### ISSUE THREAD

**Issue by BenedictWilkins** [ryanrudes/chess-gym#1]
Encoding moves with the alpha zero environment doesnt seem to like pawn under promotions given in UCI format, e.g. f2f1n 

I am using the python-chess package to create a move from PGN format (e.g. f1=N) and getting the alpha zero encoding with env.encode(move).

Am I doing something wrong?

**Comment by ryan59871** [comment]
It's not clear exactly what you are referring to. This package has nothing to do with AlphaZero, nor is there a method `env.encode()`. Are you referring to [this](https://github.com/Ryan-Rudes/AlphaZero-gym)?

**Comment by BenedictWilkins** [comment]
Apologies. I followed the link from pypi chess-gym, but actually the package I am using is gym-chess! (this is not confusing at all...)

My bad, sorry for taking up your time!
