### ISSUE TITLE
Install doesnt produce a working package on ubuntu with py3.10

### ISSUE THREAD

**Issue by MTRNord** [ryanrudes/chess-gym#3]
Somehow only the egg files are generated but not the code bundled. This is both for git and pip install ways.

I solved this for now by porting this to a `pyproject.toml` which seems to work:

```
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {name = "Ryan Rudes", email = "ryanrudes@gmail.com"},
]
dependencies = [
  'gym[classic_control]',
  'python-chess',
  'numpy',
  'cairosvg',
  'pillow',
]

description = "OpenAI Gym environment for Chess, using the game engine of the python-chess module"
name = "chess_gym"
readme = "README.md"
requires-python = ">=3.7"
version = "0.0.6"

[project.urls]
"Bug Tracker" = "https://github.com/Ryan-Rudes/chess-gym/issues"
"Homepage" = "https://github.com/Ryan-Rudes/chess-gym"
```

However, this probably should be fixed.

Also it would be nice to have accurate dependency versions. As this currently seems to fail with `ImportError: cannot import name 'rendering' from 'gym.envs.classic_control' (/home/marcel/.local/lib/python3.10/site-packages/gym/envs/classic_control/__init__.py)` on latest gym

**Comment by MTRNord** [comment]
It seems like the used module was removed entirely: https://github.com/openai/gym/pull/2599

**Comment by ryan59871** [comment]
Yes, please use an installation of `gym` prior to version 0.22.0
